# Numpy and Pandas

Data analyst 
- SQL
- One shot Query
- Programmers - MNC
- Power BI - Charts

Data Scientist
- Excel
- Line by line (Step)
- Python libraries - numpy and pandas
- Open-source
- Scale well
- Scikit - Data predictions
- Matplotlib,, seaborn - Charts

In [57]:
#%pip install numpy

## Shortcuts
- `ctrl+alt+enter` -> Run the cell
- `shift+enter` -> Move to the next cell

## Numpy
- Work with Arrays
- Performance
- C language
- Statistical oriented programming

In [58]:
import numpy as np
from datetime import datetime


In [59]:
marks = np.array([90, 80, 20, 40])
marks_list = [90, 80, 20, 40]
marks_list * 2 # This doubles the size of the array
marks * 2 # Double every element in the array

array([180, 160,  40,  80])

In [60]:
# double all the elements in marks_list
#%%time # Time function
marks_listst = [mark * 2 for mark in marks]
marks_listst

[180, 160, 40, 80]

In [61]:
np.ones(20) # Matrices of one | can use for identity matrix
np.zeros(20) # Matrices
np.arange(10) # List of integers 0-9
np.arange(1, 10, 2) # List of integers with step 2


array([1, 3, 5, 7, 9])

In [62]:
list = np.arange(1, 11) 
all_gt_five = list > 5

list[all_gt_five]

array([ 6,  7,  8,  9, 10])

### Operations
- 

## Performance
- Numpy arrays are 100 times better than 

### Matrices
- row by column
- Multiply by inverse matrix -> flip the values in the matrix (if it were a matrix of zeros and ones)
- 

In [88]:
### Task 2
# Create a 1..200 numbers and provide a numpy array with all even numbers
# Should exclude the zero
nums = np.arange(2, 201, 2)
nums

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [64]:
nums = np.arange(1, 201)
nums[nums % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [65]:
# random set of numbers
random_set = np.random.randint(18, 60, 5) # 5 Ages from 18 to 60 
random_set.tolist()

[29, 18, 31, 30, 58]

In [66]:
%%time
np.zeros(100000)

CPU times: total: 0 ns
Wall time: 0 ns


array([0., 0., 0., ..., 0., 0., 0.])

### Statistical orientations - mean, mode, median, std
- mean -> Average
- mode -> The most repeated number (most popular)
- median -> The middle number (when sorted)
- std -> Average distance between mean and 
    - A lower value -> values are closer to the mean

In [71]:
marks = np.random.randint(40, 100, 10)
marks.mean()

77.4

### Task 2
-

In [72]:
# Compound interest calculator

def compound_interest(principal, rate, years):
    return principal * (1 + rate) ** years

principal = 1000
rate = 0.05
year = 2

print(compound_interest(principal, rate, year))

1102.5


In [74]:
def calculate_interest(balance, interest):
    return balance * (1 + interest)

years = np.arange(1,11)
balance_list = []
balance = 1000
for i in years:
    balance = calculate_interest(balance, 0.05)
    balance_list.append(balance)
print(balance_list)


[1050.0, 1102.5, 1157.625, 1215.5062500000001, 1276.2815625000003, 1340.0956406250004, 1407.1004226562504, 1477.455443789063, 1551.3282159785163, 1628.8946267774422]


In [84]:
# Task 2: Balance at year 10
print(balance_list[-1])

1628.8946267774422


In [86]:
# Task 3: How much % its increased as compared to first year's balance
balance1 = balance_list[0]
balance10 = balance_list[-1]
diff = ((balance10 - balance1) / balance10) * 100
diff

35.5391083782203

In [87]:
np.std((marks))

14.779715829473853

### Useful Methods
- String methods
- Unique
- max, min


In [89]:
salaries = np.random.randint(1_000, 10_000, 10)
print(salaries)

[8125 4703 2639 1268 4502 7684 7141 1120 4290 9459]


In [92]:
print(np.max(salaries), np.argmax(salaries))
print(np.min(salaries), np.argmin(salaries))

9459 9
1120 7


In [110]:
nums = np.random.randint(1, 4, 10)
uniques = np.unique(nums)
uniques

array([1, 2, 3])

In [109]:
# reverse the array
uniques[::-1]

array([3, 2, 1])

In [111]:
np.flip(uniques)

array([3, 2, 1])

In [119]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])

items = np.char.strip(items)
items = np.char.lower(items)
items = np.unique(items)
print(items)


['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


In [123]:
# Task 2:
# a. Find and display all items that start with letter 'b'
starts_with_b = np.char.startswith(items, 'b')
items[starts_with_b]


array(['banana', 'blueberry'], dtype='<U10')

In [125]:
# b. Find and display all items that contain the letter 'e' exactly one
contains_e_once = np.char.count(items, 'e')
items[contains_e_once == 1]

array(['apple', 'cucumber', 'grape', 'lemon', 'orange', 'raspberry'],
      dtype='<U10')

In [130]:
# Task 3
hourly_visitors = np.array([468, 279,  73, 272, 406, 128, 302, 216, 140,  82])
hourly_visitors


array([468, 279,  73, 272, 406, 128, 302, 216, 140,  82])

In [ ]:
# Total visitors in the day
total_visitors = hourly_visitors.sum()
print(total_visitors)

In [ ]:
# Which is the peak hour?
pear_hour = np.max(hourly_visitors)
print(pear_hour)

In [132]:
# On average how many people visit per hour
avg_visitors = np.mean(hourly_visitors)
print(avg_visitors)

236.6


# Multi dimensional arrays

In [137]:
num_3D = np.array([[1, 3, 4],
                  [6, 10, 77],
                 [9, 20, 24]])
num_3D.shape

(3, 3)

In [141]:
nums1 = np.arange(1, 10)
nums1.shape

(9,)

In [142]:
#reshape the array
nums1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])